### ISSUE TITLE
Problem with chart (Analytics/Monitoring)

### ISSUE THREAD

**Issue by tomsawyers** [gravitee-io/release#22]
The Chart is not displayed on Analytics/Monitoring with  Gravitee 0.6.0 / Elasticsearch version : 1.7.4

There is no error on elasticsearch, the cluster is ok.

Here you can find the error on gravitee.log.

[gravitee-listener-30] ERROR i.g.m.s.impl.AnalyticsServiceImpl - An unexpected error occurs while searching for analytics data.
java.lang.NullPointerException: null
        at io.gravitee.repository.elasticsearch.analytics.ElasticAnalyticsRepository.toHistogramResponse(ElasticAnalyticsRepository.java:222) ~[gravitee-repository-elasticsearch-0.5.0.jar:na]
        at io.gravitee.repository.elasticsearch.analytics.ElasticAnalyticsRepository.hitsByApi(ElasticAnalyticsRepository.java:163) ~[gravitee-repository-elasticsearch-0.5.0.jar:na]
        at io.gravitee.repository.elasticsearch.analytics.ElasticAnalyticsRepository.query(ElasticAnalyticsRepository.java:76) ~[gravitee-repository-elasticsearch-0.5.0.jar:na]
        at io.gravitee.management.service.impl.AnalyticsServiceImpl.runHistoricalQuery(AnalyticsServiceImpl.java:136) [gravitee-management-api-service-0.6.0.jar:na]
        at io.gravitee.management.service.impl.AnalyticsServiceImpl.apiHits(AnalyticsServiceImpl.java:122) [gravitee-management-api-service-0.6.0.jar:na]
        at io.gravitee.management.service.impl.AnalyticsServiceImpl.apiHitsByStatus(AnalyticsServiceImpl.java:56) [gravitee-management-api-service-0.6.0.jar:na]
        at io.gravitee.management.rest.resource.ApiAnalyticsResource.hits(ApiAnalyticsResource.java:79) [gravitee-management-api-rest-0.6.0.jar:na]
        at sun.reflect.GeneratedMethodAccessor115.invoke(Unknown Source) ~[na:na]

**Comment by brasseld** [comment]
See gravitee-io/gravitee-repository-elasticsearch/issues/1
